version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/usr/src
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # copy sql script to create tables
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
    postgres_data: null
